name: dimred_env_2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - fastparquet
  - umap-learn
  - pacmap==0.7.2
  - datashader
  - pip
  - pip:
      - trimap
      - openTSNE
